In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Broadcasting

1. 让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐
2. 输出数组的shape是输入数组shape的各个轴上的最大值
3. 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错
4. 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值

In [8]:
a = np.arange(0,60,10).reshape(-1,1)
print(a)
print(a.shape)

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
(6, 1)


In [9]:
b = np.arange(0,5)
print(b)
print(b.shape)

[0 1 2 3 4]
(5,)


In [10]:
c = a+b
print(c)
print(c.shape)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
(6, 5)


Because the shape of a differ from that of b, according to rule 1,the shape of b needs to be firstly changed to be of the same length of a. So we add 1 to b's shape so that it is now (1,5).

In [11]:
b.shape = 1,5
print(b)

[[0 1 2 3 4]]


Now the add() has two inputs with shapes of (6,1) and (1,5), and according to rule 2, the output array will have a length of the maximum of the input arrays on every axis. Therefore, the output array's shape will be (6,5)

Since the length of b on the 0th axis is 1, and that of a is 6, to enable them to be added together, the length of b on the 0th axis need be expanded to 6. 

In [12]:
b = b.repeat(6,axis=0)
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


And since the length of a on 1st axis is 1 and that of b is 5, to enable them to be added together on 1st axis, the length of a on 1st axis need be expanded to 5

In [13]:
a = a.repeat(5,axis=1)
print(a)

[[ 0  0  0  0  0]
 [10 10 10 10 10]
 [20 20 20 20 20]
 [30 30 30 30 30]
 [40 40 40 40 40]
 [50 50 50 50 50]]


Now this is how a and b can be added together element by element

In [15]:
print(a+b)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]


### ogrid object

In [16]:
x,y = np.ogrid[0:5,0:5]
print(x,y)

[[0]
 [1]
 [2]
 [3]
 [4]] [[0 1 2 3 4]]


ogrid[start:end:step length]

ogrid[start:end:length j]

In [18]:
x,y = np.ogrid[0:1:4j,0:1:3j]
print(x,y)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]] [[0.  0.5 1. ]]


_ogrid is not a function_

### ufunc's method

- #### reduce

In [24]:
np.add.reduce([1,2,3])
# 1+2+3
np.add.reduce([[1,2,3],[4,5,6]],axis=1)
# 1,4+2,5+3,6

array([ 6, 15])

- #### accumulate

In [27]:
np.add.accumulate([1,2,3])
# 1,1+2,1+2+3
np.add.accumulate([[1,2,3],[4,5,6]],axis=1)
# 1,1+2,1+2+3
# 4,4+5,4+5+6

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

- #### reduceat

In [29]:
a = np.array([1,2,3,4])
r = np.add.reduceat(a,indices=[0,1,0,2,0,3,0])
print(r)


[ 1  2  3  3  6  4 10]
