In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Broadcasting

1. 让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐
2. 输出数组的shape是输入数组shape的各个轴上的最大值
3. 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错
4. 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值

In [2]:
a = np.arange(0,60,10).reshape(-1,1)
print(a)
print(a.shape)

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
(6, 1)


In [3]:
b = np.arange(0,5)
print(b)
print(b.shape)

[0 1 2 3 4]
(5,)


In [4]:
c = a+b
print(c)
print(c.shape)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
(6, 5)


Because the shape of a differ from that of b, according to rule 1,the shape of b needs to be firstly changed to be of the same length of a. So we add 1 to b's shape so that it is now (1,5).

In [5]:
b.shape = 1,5
print(b)

[[0 1 2 3 4]]


Now the add() has two inputs with shapes of (6,1) and (1,5), and according to rule 2, the output array will have a length of the maximum of the input arrays on every axis. Therefore, the output array's shape will be (6,5)

Since the length of b on the 0th axis is 1, and that of a is 6, to enable them to be added together, the length of b on the 0th axis need be expanded to 6. 

In [6]:
b = b.repeat(6,axis=0)
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


And since the length of a on 1st axis is 1 and that of b is 5, to enable them to be added together on 1st axis, the length of a on 1st axis need be expanded to 5

In [7]:
a = a.repeat(5,axis=1)
print(a)

[[ 0  0  0  0  0]
 [10 10 10 10 10]
 [20 20 20 20 20]
 [30 30 30 30 30]
 [40 40 40 40 40]
 [50 50 50 50 50]]


Now this is how a and b can be added together element by element

In [8]:
print(a+b)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]


### ogrid object

In [9]:
x,y = np.ogrid[0:5,0:5]
print(x,y)

[[0]
 [1]
 [2]
 [3]
 [4]] [[0 1 2 3 4]]


ogrid[start:end:step length]

ogrid[start:end:length j]

In [10]:
x,y = np.ogrid[0:1:4j,0:1:3j]
print(x,y)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]] [[0.  0.5 1. ]]


_ogrid is not a function_

### ufunc's method

- **reduce**

In [11]:
np.add.reduce([1,2,3])
# 1+2+3
np.add.reduce([[1,2,3],[4,5,6]],axis=1)
# 1,4+2,5+3,6

array([ 6, 15])

- **accumulate**

In [12]:
np.add.accumulate([1,2,3])
# 1,1+2,1+2+3
np.add.accumulate([[1,2,3],[4,5,6]],axis=1)
# 1,1+2,1+2+3
# 4,4+5,4+5+6

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

-  **reduceat**

In [13]:
a = np.array([1,2,3,4])
r = np.add.reduceat(a,indices=[0,1,0,2,0,3,0])
print(r)


[ 1  2  3  3  6  4 10]


对于indices中的每个元素都会调用reduce函数计算出一个值来，因此最终计算结果的长度和indices的长度相同。结果result数组中除最后一个元素之外，都按照如下计算得出：

```
if indices[i] < indices[i+1]:
    result[i] = np.reduce(a[indices[i]:indices[i+1]])
else:
    result[i] = a[indices[i]
```
而最后一个元素如下计算:
```
np.reduce(a[indices[-1]:])
```
因此上面例子中，结果的每个元素如下计算而得
```
1 : a[0] = 1
2 : a[1] = 2
3 : a[0] + a[1] = 1 + 2
3 : a[2] = 3
6 : a[0] + a[1] + a[2] =  1 + 2 + 3 = 6
4 : a[3] = 4
10: a[0] + a[1] + a[2] + a[4] = 1+2+3+4 = 10
```

- **outer**

In [14]:
x = np.multiply.outer([1,2,3,4,5],[2,3,4])
print(x)

[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]
 [10 15 20]]


outer方法计算的结果是如下的乘法表：
```
        2,3,4
1
2
3
4
5
```

### Matrix

In [15]:
a = np.matrix([[1,2,3],[5,5,6],[7,9,9]])
print(a*a**-1)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 4.4408921e-16  1.0000000e+00  4.4408921e-16]
 [ 0.0000000e+00 -4.4408921e-16  1.0000000e+00]]


In [16]:
a = np.array([1,2,3])
print(a)
a.reshape((-1,1))
print(a)
a.reshape((1,-1))
print(a)

[1 2 3]
[1 2 3]
[1 2 3]


- **dot**

In [17]:
"""dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])"""
a = np.arange(12).reshape(2,3,2)
b = np.arange(12,24).reshape(2,2,3)
c = np.dot(a,b)
print(a)
print("----------------")
print(b)
print("----------------")
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
----------------
[[[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
----------------
[[[[ 15  16  17]
   [ 21  22  23]]

  [[ 69  74  79]
   [ 99 104 109]]

  [[123 132 141]
   [177 186 195]]]


 [[[177 190 203]
   [255 268 281]]

  [[231 248 265]
   [333 350 367]]

  [[285 306 327]
   [411 432 453]]]]


- **inner**

In [18]:
"""inner(a,b)[i,j,k,m] = sum(a[i,j,:]*b[k,m,:])"""
a = np.arange(12).reshape(2,3,2)
b = np.arange(12,24).reshape(2,3,2)
c = np.inner(a,b)
print(a)
print("----------------")
print(b)
print("----------------")
print(c)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
----------------
[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
----------------
[[[[ 13  15  17]
   [ 19  21  23]]

  [[ 63  73  83]
   [ 93 103 113]]

  [[113 131 149]
   [167 185 203]]]


 [[[163 189 215]
   [241 267 293]]

  [[213 247 281]
   [315 349 383]]

  [[263 305 347]
   [389 431 473]]]]


- **outer**

In [19]:
x = np.outer([1,2,3],[4,5,6,7])
print(x)

[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]


- **solve**

In [20]:
a = np.random.rand(10,10)
b = np.random.rand(10)
x = np.linalg.solve(a,b)
print(x)
y = np.sum(np.abs(np.dot(a,x)-b))
print(y)

[-0.28554572 -0.74739502 -2.78688047 -0.04325806  0.51388916  1.83064682
 -0.028121    1.25658474 -0.30959697  2.628011  ]
2.831068712794149e-15


### File

In [21]:
a = np.arange(0,12)
print(a)
a.shape=3,4
print(a)
a.tofile("a.bin")
b = np.fromfile("a.bin",dtype=np.float)
print(b) # b values are not correct

print(a.dtype) # int32
b = np.fromfile("a.bin",dtype=np.int32)
print(b) # now b values are correct, one-dimensional array
b.shape = 3,4
print(b) # now b is the same as a

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[2.12199579e-314 6.36598737e-314 1.06099790e-313 1.48539705e-313
 1.90979621e-313 2.33419537e-313]
int32
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
"""
or we may use np.save() and np.load()
"""
np.save("a.npy",a)
c = np.load("a.npy")
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
"""
save multiple arrays into one file
"""
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.arange(0,1.0,0.1)
print(b)
c = np.sin(b)
print(c)
np.savez("result.npz",a,b,sin_array = c)
r = np.load("result.npz")
print(r["arr_0"])
print(r["arr_1"])
print(r["sin_array"])

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]


In [24]:
"""use savetxt and loadtxt to read/write 1-D/2-D array"""
a = np.arange(0,12,0.5).reshape(4,-1)
print(a)
np.savetxt("a.txt",a)
b = np.loadtxt("a.txt")
print(b)

np.savetxt("a_.txt",a,fmt="%d",delimiter=",") # save as integer and seperated with ,
c = np.loadtxt("a_.txt",delimiter=",")
print(c)

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
[[ 0.  0.  1.  1.  2.  2.]
 [ 3.  3.  4.  4.  5.  5.]
 [ 6.  6.  7.  7.  8.  8.]
 [ 9.  9. 10. 10. 11. 11.]]


In [25]:
a = np.arange(8)
b = np.add.accumulate(a)
c = a+b
print(a)
print(b)
print(c)
f = open("results.npy","wb")
np.save(f,a)
np.save(f,b)
np.save(f,c)
f.close()
f = open("results.npy","rb")
x = np.load(f)
print(x)
y = np.load(f)
print(y)
z = np.load(f)
print(z)

[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]
[ 0  2  5  9 14 20 27 35]
[0 1 2 3 4 5 6 7]
[ 0  1  3  6 10 15 21 28]
[ 0  2  5  9 14 20 27 35]
